[package]
name = "autd3capi-emulator"
version = "29.0.0-rc.13"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/shinolab/autd3-capi-emulator"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
autd3capi-driver = { version = "=29.0.0-rc.13" }
autd3-emulator = { version = "=29.0.0-rc.13", features = ["async-trait", "gpu", "inplace"] }
tracing-subscriber = { version = "=0.3.19", features = ["ansi", "env-filter"], default-features = false }
tracing = { version = "=0.1.41", default-features = false }
