[package]
name = "autd3capi-emulator"
version = "35.0.1"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2024"
license = "MIT"
repository = "https://github.com/shinolab/autd3-capi-emulator"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
autd3capi-driver = { version = "35.0.1", default-features = false }
autd3-emulator = { version = "36.0.1", features = ["gpu", "inplace"], default-features = false }
tracing-subscriber = { version = "=0.3.19", features = ["ansi", "env-filter"], default-features = false }
tracing = { version = "=0.1.41", default-features = false }
bytemuck = { version = "=1.23.1", default-features = false, features = ["derive"] }
