[package]
name = "license-checker"
version = "37.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.96"
cargo-license = "0.7.0"
cargo_metadata = "0.21.0"
